batch_size: 4
eval_split: test
exp_name: aaa
learning_rate: 0.0001
loss_fn: MSE
main_backbone: resnet50
optimizer: Adam
patience: 10
s1_backbone: mit_b1
s2_backbone: mit_b1
save_dir: /home/spaul/group/main/sandbox
seg_architecture: UNet
seg_dataset: inital_test
task: height_estimation
tb_path: /home/spaul/group/main/tb
